driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: fedora-25

suites:
  - name: default
    run_list:
      - recipe[yum-fedora::default]
