settings:
  parallel: true

driver:
  name: docker
  # privileged is required otherwise the container doesn't boot right
  privileged: true

platforms:
- name: fedora-22
  driver:
    image: fedora:22
    platform: fedora

suites:
  - name: default
    run_list:
      - recipe[yum-fedora::default]
