---
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITAL_OCEAN_API_KEY'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: fedora-20
  driver_plugin: digitalocean
  driver_config:
    image_id: 3243145
    flavor_id: 63
    region_id: 8
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

suites:
- name: default
  run_list:
  - recipe[yum-fedora::default]
  attributes: {}
