driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: fedora-latest
  driver:
    image: fedora:latest

suites:
  - name: default
    run_list:
      - recipe[yum-fedora::default]
