driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: current

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: fedora-latest
  driver:
    image: fedora:latest

suites:
  - name: default
    run_list:
      - recipe[yum-fedora::default]
